train:
  epochs: 2000
  batch_size: 48
  lr: 0.0003
  lr_patience: 200
model:
  hidden_size: 128                   
  num_layers: 6 
  norm: 'ln' 
  extra_feature: True
diffusion:
  num_steps: 40    
  ce_only: False 
  no_virtual_type: True