train:
  precision: 'bf16-mixed' # grid is too large to fit in fp32
  epochs: 700
  batch_size:  6 #2 # 6 for block prediction 
  lr: 0.001          #0.0003    # 0.001 for block prediction
  lr_patience: 100
  lr_warmup: 0
  lr_scheduler: 'cosine'
model:
  hidden_size: 256   
  edge_hidden: 48                
  num_layers: 10
  norm: 'ln' 
  input_residual: True
  add_transpose: True
  use_relative_blockid: True
  use_absolute_blockid: False
diffusion:
  max_hops: 1
  num_steps: 50 
  noise_schedule_type: 'cosine'
  ce_only: False 
  ce_coeff: 0.1
  uniform_noise: True    
  blockwise_time: False    
  combine_training: False 